using System.Collections.Immutable;
using VL.Core;

namespace VL.OCIO;

/// <summary>
/// Represents a single color grading instance that can be controlled via the web UI.
/// The service starts automatically — just place this node and the web UI becomes available.
///
/// Settings are persisted as a single JSON string in the "Settings Json" Create pin.
/// In editor mode, the service calls SetPinValue to update this pin (supports undo, document save).
/// In exported mode, the service uses JSON files + runtime state overrides.
/// </summary>
[ProcessNode]
public class ColorGradingInstance : IDisposable
{
    private readonly NodeContext _nodeContext;
    private readonly string _autoGeneratedId;
    private readonly bool _isExported;
    private readonly ColorGradingService _service;
    private string _lastCustomId = "";
    private bool _registered;

    // Cached parsed settings from the settingsJson Create pin
    private string _lastSettingsJson = "";
    private ProjectSettings _parsedSettings = new();

    // Runtime state overrides (used in exported mode to override Create pin defaults)
    private ColorCorrectionSettings? _runtimeColorCorrection;
    private TonemapSettings? _runtimeTonemap;
    private string? _runtimeInputFilePath;
    private bool _hasRuntimeState;

    public ColorGradingInstance(NodeContext nodeContext)
    {
        _nodeContext = nodeContext;
        _isExported = nodeContext.AppHost.IsExported;
        _autoGeneratedId = GenerateIdFromPath(nodeContext.Path.Stack);
        _service = ColorGradingService.GetOrCreate(nodeContext.AppHost);

        Console.WriteLine($"[ColorGradingInstance] Created instance '{_autoGeneratedId}' (exported: {_isExported})");
    }

    /// <summary>
    /// Main update method called every frame by VVVV.
    /// The settingsJson Create pin holds the persisted state as a JSON string.
    /// The service updates this pin via SetPinValue when settings change in the web UI.
    /// </summary>
    /// <param name="outColorCorrection">Output: effective color correction settings</param>
    /// <param name="outTonemap">Output: effective tonemap settings</param>
    /// <param name="outInputFilePath">Output: effective input file path</param>
    /// <param name="effectiveInstanceId">Output: the actual instance ID being used</param>
    /// <param name="serverPort">Output: the port the web UI server is running on</param>
    /// <param name="clientCount">Output: number of connected web UI clients</param>
    /// <param name="customInstanceId">Custom instance ID (empty = auto-generated from node path)</param>
    /// <param name="settingsJson">Create pin: serialized ProjectSettings JSON (persisted in document)</param>
    public void Update(
        out ColorCorrectionSettings outColorCorrection,
        out TonemapSettings outTonemap,
        out string outInputFilePath,
        out string effectiveInstanceId,
        out int serverPort,
        out int clientCount,
        string customInstanceId = "",
        string settingsJson = "")
    {
        // Parse settingsJson only when it changes (avoid per-frame deserialization)
        if (settingsJson != _lastSettingsJson)
        {
            _lastSettingsJson = settingsJson;
            if (!string.IsNullOrWhiteSpace(settingsJson))
            {
                var parsed = ProjectSettings.FromJson(settingsJson);
                if (parsed != null)
                {
                    _parsedSettings = parsed;
                }
            }
            else
            {
                _parsedSettings = new ProjectSettings();
            }
        }

        // Determine effective instance ID
        effectiveInstanceId = string.IsNullOrWhiteSpace(customInstanceId)
            ? _autoGeneratedId
            : customInstanceId.Trim();

        // Handle registration changes
        bool idChanged = effectiveInstanceId != _lastCustomId;

        if (idChanged)
        {
            // Unregister old ID
            if (_registered && !string.IsNullOrEmpty(_lastCustomId))
            {
                _service.UnregisterInstance(_lastCustomId);
            }

            // Register with new ID
            _service.RegisterInstance(
                effectiveInstanceId,
                _nodeContext.Path.Stack,
                _isExported,
                this,
                _parsedSettings.ColorCorrection,
                _parsedSettings.Tonemap,
                _parsedSettings.InputFilePath);

            _lastCustomId = effectiveInstanceId;
            _registered = true;
        }
        else if (_registered)
        {
            // Update the registered state if Create pin values changed
            _service.UpdateInstanceDefaults(
                effectiveInstanceId,
                _parsedSettings.ColorCorrection,
                _parsedSettings.Tonemap,
                _parsedSettings.InputFilePath);
        }

        // Determine output values: runtime override (if set) or parsed settings
        if (_hasRuntimeState && _isExported)
        {
            outColorCorrection = _runtimeColorCorrection ?? _parsedSettings.ColorCorrection;
            outTonemap = _runtimeTonemap ?? _parsedSettings.Tonemap;
            outInputFilePath = _runtimeInputFilePath ?? _parsedSettings.InputFilePath;
        }
        else
        {
            outColorCorrection = _parsedSettings.ColorCorrection;
            outTonemap = _parsedSettings.Tonemap;
            outInputFilePath = _parsedSettings.InputFilePath;
        }

        // Diagnostic outputs from the service
        serverPort = _service.ActualPort;
        clientCount = _service.ClientCount;
    }

    /// <summary>
    /// Called by the service (in exported mode) to set runtime state that overrides Create pin defaults.
    /// </summary>
    public void SetRuntimeState(
        ColorCorrectionSettings? colorCorrection,
        TonemapSettings? tonemap,
        string? inputFilePath)
    {
        _runtimeColorCorrection = colorCorrection;
        _runtimeTonemap = tonemap;
        _runtimeInputFilePath = inputFilePath;
        _hasRuntimeState = colorCorrection != null || tonemap != null || inputFilePath != null;
    }

    /// <summary>
    /// Clear runtime state, reverting to Create pin defaults.
    /// </summary>
    public void ClearRuntimeState()
    {
        _runtimeColorCorrection = null;
        _runtimeTonemap = null;
        _runtimeInputFilePath = null;
        _hasRuntimeState = false;
    }

    /// <summary>
    /// Get the node stack for SetPinValue operations (editor mode).
    /// </summary>
    public ImmutableStack<UniqueId> GetNodeStack() => _nodeContext.Path.Stack;

    /// <summary>
    /// Whether this instance is running in exported (standalone) mode.
    /// </summary>
    public bool IsExported => _isExported;

    /// <summary>
    /// Generate a human-readable instance ID from the node path.
    /// </summary>
    private static string GenerateIdFromPath(ImmutableStack<UniqueId> stack)
    {
        foreach (var uniqueId in stack)
        {
            if (uniqueId.IsDefault)
                continue;

            var idStr = uniqueId.ToString();
            var parts = idStr.Split(new[] { '/', '\\' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length > 0)
            {
                var lastPart = parts[^1];
                var cleanName = System.Text.RegularExpressions.Regex.Replace(lastPart, @"_\d+$", "");
                if (!string.IsNullOrWhiteSpace(cleanName))
                {
                    return cleanName;
                }
            }
        }

        return $"Instance_{stack.GetHashCode():X8}";
    }

    public void Dispose()
    {
        if (_registered && !string.IsNullOrEmpty(_lastCustomId))
        {
            _service.UnregisterInstance(_lastCustomId);
            _registered = false;
        }

        Console.WriteLine($"[ColorGradingInstance] Disposed instance '{_autoGeneratedId}'");
    }
}
